# Generated by Django 3.1.2 on 2020-10-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_business_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='averagerating',
            field=models.FloatField(default=0),
        ),
    ]
